### PR TITLE
Proposal for issue#30: Splitting long ways

### PR DESCRIPTION
**Pull request by flire**

### CODE REVIEW

**Comment by pnorman** [comment]
Is there anything in particular that needs scrutiny? Otherwise it looks good and I'll merge it untested.

**Comment by flire** [comment]
I have second thought about the following case: when a way doesn't belong to a relation, a new relation will be created, and all the parts of the way will get empty role (""). I've considered to assign "outer" role, but in that case a splitted way should be closed to form a multipolygon, which isn't always true. Other than that everything should be fine.

**Comment by pnorman** [comment]
If it's a way from a LINESTRING it shouldn't result in a relation at all

**Comment by flire** [comment]
So should it just be splitted without any additional info that a bunch of ways was a single linestring? And considering the fact I split ways after the parsing, I should store some kind of info what type a feature had before splitting. It's not a big deal though, I'll implement that and update the pull request.

**Comment by flire** [comment]
Updated.

**Comment by pnorman** [comment]
> So should it just be splitted without any additional info that a bunch of ways was a single linestring?

Yes

**Comment by flire** [comment]
> > So should it just be splitted without any additional info that a bunch of ways was a single linestring?
> Yes
The current version should do exactly this: parts of a polygon are joined within a relation, parts of a line become separate ways.

**Comment by pnorman** [comment]
merged, and granted commit access.

As you might have noticed, I'm not very active with ogr2osm these days, having other priorities at present.

**Pull request merged**
